CREATE TABLE [dbo].[Users]
(
    [Id] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_Users] PRIMARY KEY,
    [UserName] NVARCHAR(100) NOT NULL CONSTRAINT [UQ_Users_UserName] UNIQUE,
    [DisplayName] NVARCHAR(200) NOT NULL,
    [Email] NVARCHAR(256) NULL,
    [CreatedAtUtc] DATETIME2(3) NOT NULL CONSTRAINT [DF_Users_CreatedAtUtc] DEFAULT (SYSUTCDATETIME())
);


